using System.Collections.Generic;
using UnityEngine;

public class EnemyPortal : MonoBehaviour
{

    [SerializeField] private List<Waypoint> waypointList;
    [SerializeField] private float spawnCooldown;
    private float spawnTimer;

    public List<GameObject> enemiesToCreate;

    private void Awake()
    {
        CollectWaypoints();
    }

    private void Update()
    {
        if(CanMakeNewEnemy())
            CreateEnemy();
    }

    private bool CanMakeNewEnemy()
    {
        spawnTimer -= Time.deltaTime;

        if (spawnTimer <= 0 && enemiesToCreate.Count > 0)
        {
            spawnTimer = spawnCooldown;
            return true;
        }
        return false;
    }

    private void CreateEnemy()
    {
        GameObject randomEnemy = GetRandomEnemy();
        GameObject newEnemy = Instantiate(randomEnemy, transform.position, Quaternion.identity);

        Enemy enemyScript = newEnemy.GetComponent<Enemy>();
        if (enemyScript != null)
        {
            enemyScript.SetupEnemy(waypointList);
        }
        else
        {
            Debug.LogWarning("Enemy script not found on the instantiated enemy.");
        }
    }

    private GameObject GetRandomEnemy()
    {
        int randomIndex = Random.Range(0, enemiesToCreate.Count);
        GameObject choosenEnemy = enemiesToCreate[randomIndex];

        enemiesToCreate.Remove(choosenEnemy);

        return choosenEnemy;
    }

    public List<GameObject> GetEnemyList() => enemiesToCreate;

    private void CollectWaypoints()
    {
        waypointList = new List<Waypoint>();

        foreach(Transform child in transform)
        {
            Waypoint waypoint = child.GetComponent<Waypoint>();
            if (waypoint != null)
            {
                waypointList.Add(waypoint);
            }
        }
    }
}
